from . import owner
from . import property
from . import sale_order
from . import tag
from . import client
from . import res_partner
from . import building
from . import property_history
from . import account_move